license_id: "cc-by-igo"
caveats: "Please see [About FTS](https://fts.unocha.org/content/about-fts-what-fts)"
methodology: "Other"
methodology_other: "FTS is open to all government and private donors, funds, recipient agencies and implementing organizations wishing to report financial pledges and contributions for humanitarian action. FTS team curates the reported data by manually reviewing, validating and reconciling incoming information and updating FTS data records on an ongoing basis."
dataset_source: "OCHA Financial Tracking Service"
private: False  # has to be True or False
