license_id: "cc-by-igo"
subnational: 1  # has to be 0 or 1
notes: "FTS publishes data on humanitarian funding flows as reported by donors and recipient organizations. It presents all humanitarian funding to a country and funding that is specifically reported or that can be specifically mapped against funding requirements stated in humanitarian response plans. The data comes from OCHA's [Financial Tracking Service](https://fts.unocha.org/), is encoded as utf-8 and the second row of the CSV contains [HXL](http://hxlstandard.org) tags."
caveats: "Please see [About FTS](https://fts.unocha.org/content/about-fts-1)"
methodology: "Other"
methodology_other: "FTS is open to all government and private donors, funds, recipient agencies and implementing organizations wishing to report financial pledges and contributions for humanitarian action. FTS team curates the reported data by manually reviewing, validating and reconciling incoming information and updating FTS data records on an ongoing basis."
dataset_source: "OCHA Financial Tracking Service"
package_creator: "mcarans"
private: False  # has to be True or False
