funding_hxl_names = {
    "date": "#date",
    "budgetYear": "#date+year+budget",
    "description": "#description+notes",
    "amountUSD": "#value+funding+total+usd",
    "srcOrganization": "#org+name+funder",
    "srcOrganizationTypes": "#org+type+funder+list",
    "srcLocations": "#country+iso3+funder+list",
    "srcUsageYearStart": "#date+year+start+funder",
    "srcUsageYearEnd": "#date+year+end+funder",
    "destPlan": "#activity+appeal+name",
    "destPlanCode": "#activity+appeal+id+external",
    "destPlanId": "#activity+appeal+id+fts_internal",
    "destOrganization": "#org+name+impl",
    "destOrganizationTypes": "#org+type+impl+list",
    "destGlobalClusters": "#sector+cluster+name+list",
    "destLocations": "#country+iso3+impl+list",
    "destProject": "#activity+project+name",
    "destProjectCode": "#activity+project+code",
    "destEmergency": "#crisis+name",
    "destUsageYearStart": "#date+year+start+impl",
    "destUsageYearEnd": "#date+year+end+impl",
    "contributionType": "#financial+contribution+type",
    "flowType": "#financial+contribution+type",
    "method": "#financial+method",
    "boundary": "#financial+direction",
    "onBoundary": "#financial+direction+type",
    "status": "#status+text",
    "firstReportedDate": "#date+reported",
    "decisionDate": "#date+decision",
    "keywords": "#description+keywords",
    "originalAmount": "#value+funding+total",
    "originalCurrency": "#value+funding+total+currency",
    "exchangeRate": "#financial+fx",
    "id": "#activity+id+fts_internal",
    "refCode": "#activity+code",
    "createdAt": "#date+created",
    "updatedAt": "#date+updated",
}

hxl_names = {
    "countryCode": "#country+code",
    "id": "#activity+appeal+id+fts_internal",
    "name": "#activity+appeal+name",
    "code": "#activity+appeal+id+external",
    "typeId": "#activity+appeal+type+id+fts_internal",
    "typeName": "#activity+appeal+type+name",
    "startDate": "#date+start",
    "endDate": "#date+end",
    "year": "#date+year",
    "clusterCode": "#sector+cluster+code",
    "cluster": "#sector+cluster+name",
    "requirements": "#value+funding+required+usd",
    "funding": "#value+funding+total+usd",
    "percentFunded": "#value+funding+pct",
    "covidFunding": "#value+funding+covid+usd",
    "covidPercentageOfFunding": "#value+funding+covid+pct",
}

rename_columns = {
    "totalFunding": "funding",
    "revisedRequirements": "requirements",
    "clusterName": "cluster",
}
country_all_columns_to_keep = [
    "date",
    "budgetYear",
    "description",
    "amountUSD",
    "srcOrganization",
    "srcOrganizationTypes",
    "srcLocations",
    "srcUsageYearStart",
    "srcUsageYearEnd",
    "destPlan",
    "destPlanCode",
    "destPlanId",
    "destOrganization",
    "destOrganizationTypes",
    "destGlobalClusters",
    "destLocations",
    "destProject",
    "destProjectCode",
    "destEmergency",
    "destUsageYearStart",
    "destUsageYearEnd",
    "contributionType",
    "flowType",
    "method",
    "boundary",
    "onBoundary",
    "status",
    "firstReportedDate",
    "decisionDate",
    "keywords",
    "originalAmount",
    "originalCurrency",
    "exchangeRate",
    "id",
    "refCode",
    "createdAt",
    "updatedAt",
]
country_emergency_columns_to_keep = [
    "id",
    "name",
    "code",
    "startDate",
    "endDate",
    "year",
    "revisedRequirements",
    "totalFunding",
    "percentFunded",
]
plan_columns_to_keep = [
    "clusterCode",
    "clusterName",
    "revisedRequirements",
    "totalFunding",
]
cluster_columns_to_keep = [
    "countryCode",
    "id",
    "name",
    "code",
    "startDate",
    "endDate",
    "year",
    "clusterCode",
    "clusterName",
    "revisedRequirements",
    "totalFunding",
]
